<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>YPNUS AI: Build Your Mortgage Consultant Website in Minutes | Professional AI Website Builder</title>
<meta name="description" content="YPNUS AI: Build a professional, NMLS 1230391 compliant mortgage consultant website in 2 minutes. AI lead capture, auto follow-up. 2,400+ consultants trust YPNUS. Try free.">
<link rel="canonical" href="https://ypnus.com/">
<meta name="robots" content="index, follow">
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Plus+Jakarta+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">
<script src="https://cdn.tailwindcss.com"></script>
<script>tailwind.config = {theme: { extend: {fontFamily: { serif: ['DM Serif Display', 'serif'], sans: ['Plus Jakarta Sans', 'sans-serif'] },colors: { navy: '#0A1F44', gold: '#C9A961', ivory: '#F9F7F4' }}}}</script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YN9WTJSEKP"></script>
<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-YN9WTJSEKP');</script>
<style>body { font-family: 'Plus Jakarta Sans', sans-serif; color: #0A1F44; }.serif { font-family: 'DM Serif Display', serif; }.btn-primary { transition: all 0.3s ease; }.btn-primary:hover { transform: translateY(-2px); box-shadow: 0 12px 32px rgba(10, 31, 68, 0.15); }.btn-secondary { transition: all 0.3s ease; border: 1.5px solid #0A1F44; }.btn-secondary:hover { background: #0A1F44; color: #F9F7F4; }.fade-in-1 { animation: fadeIn 0.8s ease-out 0.1s forwards; opacity: 0; }.fade-in-2 { animation: fadeIn 0.8s ease-out 0.2s forwards; opacity: 0; }.fade-in-3 { animation: fadeIn 0.8s ease-out 0.3s forwards; opacity: 0; }.fade-in-4 { animation: fadeIn 0.8s ease-out 0.4s forwards; opacity: 0; }@keyframes fadeIn { to { opacity: 1; } }.section-py { padding: 6rem 1rem; }@media (max-width: 768px) { .section-py { padding: 4rem 1rem; } }.divider { height: 1px; background: linear-gradient(to right, transparent, #C9A961, transparent); }</style>
<script type="application/ld+json">{"@context": "https://schema.org","@type": "Organization","name": "YPNUS AI","url": "https://ypnus.com","identifier": "NMLS 1230391","areaServed": "US"}</script>
<script type="application/ld+json">{"@context": "https://schema.org","@type": "FAQPage","mainEntity": [{"@type":"Question","name":"Is my website NMLS compliant?","acceptedAnswer":{"@type":"Answer","text":"Yes. NMLS 1230391 compliance is built-in. TCPA, licensing, disclosures handled automatically."}},{"@type":"Question","name":"Can I use my own domain?","acceptedAnswer":{"@type":"Answer","text":"Yes. Connect any domain. We handle SSL and DNS."}}]}</script>
</head>
<body class="antialiased bg-white">
<nav class="fixed top-0 w-full bg-white/90 backdrop-blur z-50 border-b"><div class="max-w-7xl mx-auto px-6 py-3 flex justify-between items-center"><div class="serif text-2xl font-bold text-navy">YPNUS AI</div><button onclick="scrollToCTA()" class="px-6 py-2 rounded-full bg-navy text-white font-semibold">Try Free</button></div></nav>
<section class="pt-32 pb-20 px-6 bg-white text-center"><div class="max-w-4xl mx-auto"><span class="inline-block px-4 py-1.5 rounded-full bg-gold/20 text-gold text-sm font-semibold mb-4 fade-in-1">NMLS 1230391 • TCPA Compliant</span><h1 class="serif text-5xl md:text-7xl font-bold text-navy mb-6 fade-in-1">Build Your Mortgage<br/>Consultant Website<br/>With <span class="text-gold">AI.</span> In Minutes.</h1><p class="text-lg text-gray-600 mb-8 fade-in-2">Professional. Compliant. Auto lead capture. Used by 2,400+ mortgage professionals.</p><div class="flex flex-col md:flex-row gap-4 justify-center fade-in-3"><button onclick="scrollToCTA(); gtag('event','hero_cta')" class="btn-primary px-8 py-4 rounded-full bg-navy text-white font-semibold text-lg">✨ Try for Free</button><button class="btn-secondary px-8 py-4 rounded-full text-navy font-semibold text-lg">Watch Demo</button></div><p class="text-sm text-gray-500 mt-6 fade-in-4">✓ No credit card • ✓ Deploy instantly • ✓ 2,400+ professionals</p><div class="mt-12 max-w-2xl mx-auto text-left"><div class="bg-slate-100 p-6 rounded-xl"><p class="text-sm text-slate-600 mb-3">See your AI site instantly:</p><input id="nmlsInput" placeholder="Enter your NMLS #" class="w-full px-4 py-3 rounded-lg border mb-3"><button onclick="generatePreview()" class="w-full btn-primary px-6 py-3 bg-gold text-navy rounded-lg font-semibold">Generate Preview</button><div id="preview" class="mt-4 hidden bg-white p-4 rounded border"></div></div></div></div></section>
<div class="divider mx-6 max-w-7xl mx-auto"></div>
<section id="features" class="section-py bg-ivory"><div class="max-w-7xl mx-auto"><h2 class="serif text-4xl font-bold text-navy text-center mb-12 fade-in-1">AI-Powered for Mortgage Professionals</h2><div class="grid md:grid-cols-4 gap-8"><div class="text-center fade-in-1"><h3 class="serif text-xl font-bold mb-2">Deploy in Minutes</h3><p class="text-gray-600 text-sm">No coding. Site live instantly.</p></div><div class="text-center fade-in-2"><h3 class="serif text-xl font-bold mb-2">100% Compliant</h3><p class="text-gray-600 text-sm">NMLS 1230391 + TCPA built-in.</p></div><div class="text-center fade-in-3"><h3 class="serif text-xl font-bold mb-2">AI Lead Capture</h3><p class="text-gray-600 text-sm">Auto scored + follow-up.</p></div><div class="text-center fade-in-4"><h3 class="serif text-xl font-bold mb-2">AI Optimization</h3><p class="text-gray-600 text-sm">Daily A/B testing.</p></div></div></div></section>
<section id="pricing" class="section-py bg-white"><div class="max-w-7xl mx-auto"><h2 class="serif text-4xl font-bold text-navy text-center mb-12">Simple Pricing</h2><div class="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto"><div class="border-2 border-gray-200 p-8 rounded-2xl"><h3 class="serif text-2xl font-bold mb-2">Starter</h3><p class="text-gold text-3xl font-bold">Free</p><p class="text-sm mb-6">Forever</p><ul class="text-sm space-y-2 mb-8"><li>✓ AI site</li><li>✓ 10 leads/mo</li><li>✓ NMLS compliance</li></ul><button onclick="scrollToCTA()" class="w-full btn-secondary py-3 rounded-lg">Start Free</button></div><div class="bg-navy text-white p-8 rounded-2xl scale-105"><h3 class="serif text-2xl font-bold mb-2">Pro</h3><p class="text-gold text-3xl font-bold">$99</p><p class="text-sm mb-6">/mo</p><ul class="text-sm space-y-2 mb-8"><li>✓ Unlimited leads</li><li>✓ AI scoring</li><li>✓ Auto follow-up</li></ul><button onclick="scrollToCTA()" class="w-full py-3 rounded-lg bg-gold text-navy font-bold">Start Trial</button></div><div class="border-2 border-gold p-8 rounded-2xl"><h3 class="serif text-2xl font-bold mb-2">Business</h3><p class="text-gold text-3xl font-bold">$249</p><p class="text-sm mb-6">/mo</p><ul class="text-sm space-y-2 mb-8"><li>✓ Everything in Pro</li><li>✓ Analytics</li><li>✓ API + Zapier</li></ul><button onclick="scrollToCTA()" class="w-full btn-secondary py-3 rounded-lg">Start Trial</button></div></div></div></section>
<section id="cta" class="section-py bg-white"><div class="max-w-3xl mx-auto text-center"><h2 class="serif text-5xl font-bold text-navy mb-4">Join 2,400+ Mortgage Professionals</h2><p class="text-xl text-gray-600 mb-8">14-day free trial. No credit card.</p><script async data-uid="9175815" src="https://convertkit.com/landing_pages/forms/9175815.js"></script><p class="text-xs text-gray-500 mt-6">By submitting, you agree to receive texts from YPNUS. Reply STOP to opt out. NMLS 1230391. Msg & data rates may apply.</p></div></section>
<footer class="bg-navy text-white py-10"><div class="max-w-7xl mx-auto px-6 text-center text-sm text-gray-300">© 2026 YPNUS Inc. | NMLS 1230391 | Equal Housing Opportunity</div></footer>
<div class="md:hidden fixed bottom-0 left-0 right-0 bg-navy p-4 z-40"><button onclick="scrollToCTA()" class="w-full py-3 bg-gold text-navy font-bold rounded-lg">Try Free</button></div>
<script>function scrollToCTA() {document.getElementById('cta').scrollIntoView({behavior:'smooth'});gtag('event','cta_click');}function generatePreview() {const nmls = document.getElementById('nmlsInput').value;const preview = document.getElementById('preview');if(nmls) {preview.innerHTML = `<strong>Preview:</strong><br>Your Name<br>Mortgage Consultant<br>NMLS ${nmls}<br><span class="text-gold">ypnus.com/yourname</span>`;preview.classList.remove('hidden');gtag('event','demo_generated');}}</script>
</body>
</html>
